[package]
name = "concurrency"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - concurrency"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["concurrency"]
publish.workspace = true
autolib = false

[dependencies]
actix = "0.13.5"
await-tree = { version = "0.3.1", features = [ "tokio" ] }
crossbeam = "0.8.4"
crossbeam-channel = "0.5.15"
crossbeam-queue = "0.3.12"
crossbeam-utils = "0.8.21"
dashmap = "6.1.0"
flume = { version = "0.11.1", features = ["select"] }
flurry = "0.5.2"
futures = "0.3.31"
parking_lot = "0.12.5"
ractor = "0.15.9"
rayon = "1.11.0"
# FIXME riker = "0.4.2"
# FIXME stakker = "0.2.11"
threadpool = "1.8.1"

## General
anyhow = "1.0.100"
glob = "0.3.3"
image = "0.25.8"
itertools = "0.14.0"
lazy_static = "1.5.0"
num = "0.4.3"
num_cpus = "1.17.0"
papaya = "0.2.3"
rand = { version = "0.9.2", features = ["thread_rng"] }
ring = "0.17.14"
time = "0.3.44"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"]  }
walkdir = "2.5.0"
