[package]
name = "filesystem"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - filesystem"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["filesystem"]
publish.workspace = true
autolib = false

[dependencies]
anyhow = "1.0.100"
camino = "1.2.1"
directories = "6.0.0"
dirs = "6.0.0"
glob = "0.3.3"
globset = "0.4.18"
ignore = "0.4.24"
memmap2 = "0.9.9"
notify = "8.2.0"
open = "5.3.2"
remove_dir_all = { version = "1.0.0", features = [ "parallel" ] }
same-file = "1.0.6"
# tempdir is outdated, replaced by tempfile
tempfile = "3.23.0"
walkdir = "2.5.0"

utils = { path =  "../../utils" }
