[package]
name = "web_programming_http_client"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - web_programming_http_client"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["web_programming_http_client"]
publish.workspace = true
autolib = false

[dependencies]
hyper = "1.7.0"
hyper-util = "0.1.17"
reqwest = { version = "0.12.24", features = ["blocking", "json", "stream"] }
ureq = "3.1.2"

## General
anyhow = "1.0.100"
http-body-util = "0.1.3"
serde = { version = "1.0.228", features = ["derive"] }
tempfile = "3.23.0"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"]  }
url = "2.5.7"
