[package]
name = "development_tools"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - development_tools"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["development_tools"]
publish.workspace = true

[dependencies]
crates_io_api = "0.12.0"
# FIXME add example doc-comment = "0.3.3"
semver = "1.0.27"

## General
anyhow = "1.0.100"
tracing = "0.1.41"
