[package]
name = "parser_implementations"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - parser_implementations"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["parser_implementations"]
publish.workspace = true
autolib = false

# FIXME
[dependencies]
basic-toml = "0.1.10"
comrak = "0.45.0"
# FIXME cssparser = "0.35.0"
# FIXME html5ever = "0.33.0"
json5 = "0.4.1"
markdown = "1.0.0"
# FIXME markup5ever = "0.16.0"
# FIXME markup5ever_arcdom = "0.1.2"
pulldown-cmark = "0.13.0"
# FIXME quick-xml = {version = "0.37.2", features = ["serialize"] }
roxmltree = "0.21.1"
rust-ini = "0.21.3"
serde_json = "1.0.145"
serde_yml = "0.0.12"
simd-json = "0.17.0"
sqlparser = { version = "0.59.0", features = ["visitor"], optional = true }
swc_ecma_parser = "25.0.0"
swc_ecma_ast = "16.0.0"
swc_common = "15.0.0"
tl = "0.7.8"
toml_edit = "0.23.7"
toml = "0.9.8"
# FIXME xml = "0.8.20"
# FIXME xml5ever = "0.23.0"
# FIXME xmlparser = "0.13.6"

## General
anyhow = "1.0.100"
chrono = { version = "0.4.42", features = [ "serde" ] }
serde = { version = "1.0.228", features = ["derive"] }

[features]
sqlparser = ["dep:sqlparser"]

[package.metadata.cargo-machete]
ignored = ["rust-ini"]
