[package]
name = "asynchronous"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - asynchronous"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["asynchronous"]
publish.workspace = true
autolib = false

[dependencies]
async-channel = "2.5.0"
# LATER async-stream = "0.3.6"
async-trait = "0.1.89"
futures = "0.3.31"
# FIXME futures-executor = "0.3.31"
futures-util = "0.3.31"
kanal = "0.1.1"                                # NOTE: pre version
# FIXME do we need an example? mio = "1.0.2"
postage = "0.5.0"
rayon = "1.11.0"
reqwest = "0.12.24"
#  FIXME need an example smol = "2.0.2"
tokio = { version = "1.48.0", features = [ "rt-multi-thread", "fs" ] }
tokio-graceful-shutdown = "0.19.0"

## General
anyhow = "1.0.100"
rand = { version = "0.9.2", features = ["thread_rng"] }
time = "0.3.44"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
