[package]
name = "development_tools_testing"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - development_tools_testing"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["development_tools_testing"]
publish.workspace = true
autolib = false

[dependencies]
# FIXME afl = "0.15.13"
approx = "0.5.1" # was pinned at 0.4.0
fake = { version = "4.4.0", features = [ "derive" ] }
faux = "0.1.13"
insta = "1.43.2"
mockall = "0.13.1"
proptest = "1.9.0"

## General
