[package]
name = "template_engine"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - template_engine"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["template_engine"]
publish.workspace = true
autolib = false

[dependencies]
tera = "1.20.0"
tinytemplate = "1.2.1"

## General
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
