[package]
name = "wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - wasm"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["wasm"]
publish.workspace = true
autolib = false

[dependencies]
# LATER add example?
# js-sys = "0.3.77"
wasmer = "6.0.1"
wasmtime = { version = "36.0.5", optional = true } # Heavy compile
yew = { version = "0.21.0", features = ["csr"] }

## General
anyhow = "1.0.95"

[features]
wasmtime = ["dep:wasmtime"]
