[package]
name = "text_processing"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - text_processing"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["text_processing"]
publish.workspace = true
autolib = false

[dependencies]
aho-corasick = "1.1.3"
bstr = "1.12.1"
concat-string = "1.0.1"
concat_strs = "1.0.2"
diff = "0.1.13"
fancy-regex = "0.16.2"
fuzzy-matcher = "0.3.7"
heck = "0.5.0"
hyphenation = "0.8.4"
indoc = "2.0.7"
joinery = "3.1.0"
memchr = "2.7.6"
regex = "1.12.2"
strsim = "0.11.1"
similar = "2.7.0"
textwrap = { version = "0.16.2", features = ["hyphenation"] }
unicode-segmentation = "1.12.0"
ustr = "1.1.0"

## General
anyhow = "1.0.100"
console = "0.16.1"
lazy_static = "1.5.0"
once_cell = "1.21.3"
libc = "0.2.177"
