[package]
name = "rust_patterns"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - rust_patterns"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["rust_patterns"]
publish.workspace = true
autolib = false

[dependencies]
anyhow = "1.0.100"
color-eyre = "0.6.5"
csv = "1.4.0"
dyn-clone = "1.0.20"
either = "1.15.0"
# FIXME frunk = "0.4.3"
im = "15.1.0"
# eyre is outdated, see color-eyre
itertools = "0.14.0"
miette = { version = "7.6.0", features = ["fancy"] }
# FIXME pin-project = "1.1.10"
# pin-project-lite = "0.2.16"
reqwest = { version = "0.12.24", features = ["blocking"] }
rpds = "1.1.2"
scopeguard = "1.2.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
