[package]
name = "data_structures"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - data_structures"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["data_structures"]
publish.workspace = true
autolib = false

# FIXME
[dependencies]
arrayvec = "0.7.6"
bitflags = "2.10.0"
bitvec = "1.0.1"
# TODO add example? bloomfilter = "3.0.1"
# TODO add example? bytes = "1.9.0"
flagset = "0.4.7"
fnv = "1.0.7"
heapless = "0.9.1" # pinned elsewhere to 0.7.17 for postcard
indexmap = "2.12.0"
# TODO add example? linked-hash-map = "0.5.6"
multimap = "0.10.1"
petgraph = "0.8.3"
priority-queue = "2.7.0"
# TODO add example? rangemap = "1.5.1"
# TODO add example? skiplist = "0.6.0"
roaring = "0.11.2"
slotmap = "1.0.7"
smallvec = "1.15.1" # alpha
tinyvec = { version = "1.10.0", features = ["alloc"] }
uuid = { version = "1.18.1", features = [
    "v4",                # Lets us generate random UUIDs.
    "fast-rng",          # Use a faster (but still sufficiently random) RNG.
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs.
] }
ulid = "1.2.1"

## General
anyhow = "1.0.100"
crates_io_api = "0.12.0"
