[package]
name = "web_programming"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - web_programming"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["web_programming"]
publish.workspace = true
autolib = false

[dependencies]
http = "1.3.1"
# FIXME http-body-util = "0.1.2"
url = "2.5.7"
reqwest = "0.12.24"
select = "0.6.1"
mime = "0.3.17"

## General
anyhow = "1.0.100"
lazy_static = "1.5.0"
regex = "1.12.2"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"]  }
