[package]
name = "authentication"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - authentication"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["authentication"]
publish.workspace = true
autolib = false

[dependencies]
reqwest = { version = "0.12.24", features = [ "blocking" ] }

## General
anyhow = "1.0.100"
