[package]
name = "caching"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - caching"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = [ "caching" ]
publish.workspace = true
autolib = false

[dependencies]
cached = "0.56.0"
lru = "0.16.3"
moka = { version = "0.12.11", features = ["sync"] }
