[package]
name = "os"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Book code examples and their crate dependencies - os"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license = "CC0-1.0"
keywords.workspace = true
categories = ["os"]
publish.workspace = true
autolib = false

[dependencies]
libc = "0.2.177"
which = "8.0.0"

## General
anyhow = "1.0.100"
regex = "1.12.2"
